### ISSUE TITLE
Improvements to EDF Scripts

### ISSUE THREAD

**Issue by timgdavies** [openownership/openownership.beta#34]
From @stevenday in reference to the scripts added in #33:

- scripts/update_framework.py
- scripts/framework_to_yaml.py

Assuming this is what we're working with for now, there's a few things I'd like to see:

## On the setup
- Let's use python-dotenv, rather than a custom env.sh setup
- Can we get some documentation on how to run this in the README?
- We need a requirements.txt to pin the versions of these libraries and instructions to then run this from a virtualenv

## On the code
- What happens if we rename a framework page/section? ideally I think we want to be able to redirect users to the new one, so we need a more persistent id, but that feels like a trickier task to ticket for later. 
- Is the plan still to run this via a github action? Redirects notwithstanding, we'll need to remember to `git rm` everything before we run this and then `git add` afterwards, so that it picks up changes. (Presuming that's the way you're running it manually at the moment?)
- The code needs linting
- We should switch to [f-strings](https://saralgyaan.com/posts/f-string-in-python-usage-guide/#Multi-line_f-strings_in_Python) where possible
- Other code improvements are noted in the review of #33.

**Comment by stevenday** [comment]
This script has been deleted, so we can close this.
